# Source Dataset Configuration
source:
  path: "data/source.json"
  multiline: true

# Target Dataset Configuration
target:
  path: "data/target.json"
  multiline: true

# Column Configuration
columns:
  # Columns to exclude from comparison
  exclude:
    - updated_timestamp
    - etl_batch_id
  
  # Specific field mappings
  mappings:
    - source_field: id
      target_field: id
      comparison_type: exact
      tolerance: 0
    - source_field: customer_name
      target_field: customer_name
      comparison_type: exact
      tolerance: 0
    - source_field: amount
      target_field: value
      comparison_type: numeric
      tolerance: 0.01
    - source_field: transaction_date
      target_field: transaction_date
      comparison_type: exact
      tolerance: 0
    - source_field: status
      target_field: status
      comparison_type: exact
      tolerance: 0

# Reconciliation Settings
settings:
  record_count_threshold: 0.99
  field_match_threshold: 0.95
  batch_size: 100000
  key_fields:
    - id
